# This is a basic workflow to help you get started with Actions

name: delete_release

# The type of start
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'

# define workflow
jobs:
  build:
    runs-on: ubuntu-20.04
    # define steps
    steps:
      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 5
          delete_workflows: true
          workflows_keep_day: 10
          gh_token: ${{ secrets.RELEASE_TOKEN }}
